remove support for old equipment

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -94,24 +94,30 @@ jobs:
     needs: [build]
     runs-on: ubuntu-latest
     steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
       - name: Download Artifacts
         uses: actions/download-artifact@v4
         with:
           path: bin/
           merge-multiple: true
 
-      - name: Delete Current
-        uses: 8Mi-Tech/delete-release-assets-action@main
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          tag: pre-release
-          deleteOnlyFromDrafts: false
+      - name: Delete Pre-release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          if ! gh release delete pre-release --yes; then
+            echo "Failed to delete release, but continuing..."
+          fi
+          git log -1 --pretty=format:"%s%n%b" > changelog.md
 
       - name: Publish Prerelease
         if: success()
         uses: softprops/action-gh-release@v2
         with:
           tag_name: pre-release
+          body_path: changelog.md
           files: |
             bin/latest.yml
             bin/dist/*
@@ -126,20 +132,20 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Update Version
-        run:
-        INPUT_VERSION="${{ github.event.inputs.version }}"
-        CLEAN_VERSION=$(echo "$INPUT_VERSION" | sed 's/^v//')
-        if [[ ! "$CLEAN_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-          echo "Invalid version format: $INPUT_VERSION"
-          exit 1
-        fi
-        jq --arg version "$CLEAN_VERSION" '.version = $version' package.json > tmp.json && mv tmp.json package.json
+        run: |
+          INPUT_VERSION="${{ github.event.inputs.version }}"
+          CLEAN_VERSION=$(echo "$INPUT_VERSION" | sed 's/^v//')
+          if [[ ! "$CLEAN_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid version format: $INPUT_VERSION"
+            exit 1
+          fi
+          jq --arg version "$CLEAN_VERSION" '.version = $version' package.json > tmp.json && mv tmp.json package.json
 
-        git config --global user.email "github-actions[bot]@users.noreply.github.com"
-        git config --global user.name "github-actions[bot]"
-        git add package.json
-        git commit -m "Update version to $CLEAN_VERSION"
-        git push
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git config --global user.name "github-actions[bot]"
+          git add package.json
+          git commit -m "Update version to $CLEAN_VERSION"
+          git push
 
       - uses: actions/download-artifact@v4
         with:
